frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /
    host: backend.{domain}


#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

